### ISSUE TITLE
Sourcery doesn't work with Apollo GraphQL generated API.swift

### ISSUE THREAD

**Issue by va1da** [krzysztofzablocki/Sourcery#420] opened 2017-09-22 13:36 UTC
Hi,
I'm using Sourcery to generate methods for GraphQL API.
Currently as generated API.swift is about 710 KB Sourcery gets stuck (eats all my RAM and then available disk space).

I understand that there are a lot of types in API.swift, but even though, it could work on 8GB RAM notebook?

Anyone having similar issue?

Xcode 9
[API.swift.zip](https://github.com/krzysztofzablocki/Sourcery/files/1324683/API.swift.zip)

**Comment by ilyapuchka** [comment] 2017-09-22 21:52
Thanks for providing this example, we can use it in future for performance testing. For now I think Sourcery code is just not optimised to deal with very big amount of data.

**Comment by krzysztofzablocki** [comment] 2017-10-20 07:14
@va1da I'll take a look, can you share the template you have been trying to use for it?

**Comment by va1da** [comment] 2017-10-31 13:34
[GraphQLQuery.stencil.zip](https://github.com/krzysztofzablocki/Sourcery/files/1430868/GraphQLQuery.stencil.zip)

**Comment by Antondomashnev** [comment] 2017-11-29 22:53
@krzysztofzablocki FYI I've checked it a while ago and because there are plenty of nested of levels of recursion here:
```
private func walkDeclarations(source: [String: SourceKitRepresentable], containingIn: (Any, [String: SourceKitRepresentable])? = nil, processed: inout [[String: SourceKitRepresentable]], foundEntry: (SwiftDeclarationKind, String, AccessLevel, [String], [String: SourceKitRepresentable], Any?) -> Any?) {
        if let substructures = source[SwiftDocKey.substructure.rawValue] as? [SourceKitRepresentable] {
            for substructure in substructures {
                if let source = substructure as? [String: SourceKitRepresentable] {
                    processed.append(source)
                    walkDeclaration(source: source, containingIn: containingIn, foundEntry: foundEntry)
                }
            }
        }
    }
```
It ends up consuming a huge amount of memory.

**Comment by lvsti** [comment] 2018-01-22 08:37
@Antondomashnev FWIW I've put a recursion counter into `walkDeclarations` and with a similar 500+KB swift file it never exceeded 4 levels, so the culprit might not necessarily be the recursion itself.

**Comment by Antondomashnev** [comment] 2018-01-22 09:23
@lvsti hey, thanks for the follow-up. The generated Graphql file contains lots of types, so I guess that lead to the problem with recursion. But maybe I'm missing the root cause =)

**Comment by tamasprezi** [comment] 2018-02-02 22:36
After some experimentation, I managed to have the above GraphQL example run to completion with the following change: in [Substring.swift:60](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/Utils/Substring.swift#L60) replace

```swift
let substring = range(for: source).flatMap { contents.substringWithByteRange(start: Int($0.offset), length: Int($0.length)) }
```

with

```swift
let substring = range(for: source).flatMap { (contents as NSString).substring(with: NSRange(location: Int($0.offset), length: Int($0.length))) }
```

(basically skipping the SourceKittenFramework-provided string tokenizer).

Now, I'm not exactly sure if there was any particular reason to use the `String+SourceKitten` extension to get a substring with the given range, but if there wasn't then IMO the above solution is a good enough fix. Parsing of the above example is still terribly slow (3+ mins), but at least the memory high water mark remains steadily under 100 MB.

**Comment by ilyapuchka** [comment] 2018-02-02 23:01
@tamasprezi thanks for your research. The reason to use SourceKitten function is that it handles (supposed to) unicode and that SourceKitten ranges are in bytes, not in NSRange, so they are not directly convertible. It will probably make sense to raise this issue in SourceKitten itself. I guess extensive memory usage might be related to internal strings cache, used by SourceKitten for performance improvements, I guess.
/cc @jpsim

**Comment by jpsim** [comment] 2018-02-02 23:56
@tamasprezi as @ilyapuchka writes, your replacement isn't unicode safe and might either crash or return incorrect results if any of the characters in that file aren't exactly eight bits.

**Comment by tamasprezi** [comment] 2018-02-03 07:58
@ilyapuchka @jpsim thanks for the explanation, I'll try to come up with a unicode-safe solution then

**Comment by tamasprezi** [comment] 2018-02-03 16:11
Here is the improved, unicode-safe fix:

```swift
let substring = range(for: source).flatMap { range -> String? in
    guard let subdata = contents.data(using: .utf8)?.subdata(in: Int(range.offset)..<Int(range.offset + range.length)) else {
        return nil
    }
    return String(data: subdata, encoding: .utf8)
}
```

Tested it with the emojified version ([APImoji.swift.zip](https://github.com/krzysztofzablocki/Sourcery/files/1691902/APImoji.swift.zip)) of the above API.swift (`s/Graph/📈/`, `s/QL/🆒/`, `s/Query/🤔/`) and this basic stencil:

```
{% for t in types.all %}
    {{ t.name }}
{% endfor %}
```

got a nice unicode output of

```
    ActiveCheckins🤔
    ActiveCheckins🤔.Data
    ActiveCheckins🤔.Data.Me
    ActiveCheckins🤔.Data.Me.CheckedIn
    ....
```

Net execution time is around 5 mins (cache cleared beforehand), memory averages at ~100 MB. Tests pass locally. Let me know if this is fit for a PR or if I overlooked something.

**Comment by jpsim** [comment] 2018-02-03 23:03
Unfortunately, changing SourceKitten's `NSString.substringWithByteRange(...)` function to return a string created from underlying bytes from the subrange of the backing data (see https://github.com/jpsim/SourceKitten/commit/6dcbf09b70c9d5f84a323ba7e94ac194890b1b50) yielded consistently slower results than the existing approach.

I measured this by running SwiftLint's benchmark suite, which lints a given branch (in this case with this change), against `master` (which in this case is exactly the same, minus this one change). It lints a dozen Swift projects 5 times each before+after and averages the results to smooth out any unrelated deviations.

* Linting Aerial with this PR took **0.33s** vs **0.31s** on master (**6% slower**)
* Linting Alamofire with this PR took **1.94s** vs **1.7s** on master (**14% slower**)
* Linting Firefox with this PR took **8.54s** vs **7.57s** on master (**12% slower**)
* Linting Kickstarter with this PR took **11.57s** vs **11.31s** on master (**2% slower**)
* Linting Moya with this PR took **1.28s** vs **1.12s** on master (**14% slower**)
* Linting Nimble with this PR took **1.08s** vs **1.07s** on master (**0% slower**)
* Linting Quick with this PR took **0.37s** vs **0.36s** on master (**2% slower**)
* Linting Realm with this PR took **2.11s** vs **1.8s** on master (**17% slower**)
* Linting SourceKitten with this PR took **0.73s** vs **0.68s** on master (**7% slower**)
* Linting Sourcery with this PR took **3.79s** vs **2.99s** on master (**26% slower**)
* Linting Swift with this PR took **9.55s** vs **7.53s** on master (**26% slower**)
* Linting WordPress with this PR took **8.65s** vs **8.07s** on master (**7% slower**)

So unfortunately solving this isn't as simple as just replacing SourceKitten's implementation with yours, but you might have more luck making a more targeted change in Sourcery that might improve performance for its specific usage patterns.

**Comment by ilyapuchka** [comment] 2018-02-03 23:20
@jpsim that is probably why you are using some kind of cache for strings? Can it be that it is the reason of extensive memory usage why scanning large code base with SourceKitten? As I can see `CacheContainer` basically contains duplicate of string (by lines) and its utf8 view.

**Comment by jpsim** [comment] 2018-02-04 04:19
Yes, that’s exactly why I’m caching some useful data for all strings. I’d love nothing more but to find more efficient ways of doing those string operations to make caching unnecessary, but so far that’s the best I could do.

**Comment by tamasprezi** [comment] 2018-02-04 07:16
IMO the problem is not caching per se, it's that it doesn't go away when it should. See, if caching doubles the required memory then we'd have seen that Sourcery used ~200-300 MB to parse the above API.swift. Instead we see that memory consumption skyrockets through 10 GB(!) and counting. So I'm suspecting that Sourcery is just too generous in that it holds on to and lets string instances linger around way after they have done their job (deep in the recursion tree). I'm not that familiar with the codebase and so I couldn't spot the exact place where this happens, that's why I proposed a workaround and not a solution.

**Comment by jpsim** [comment] 2018-02-04 18:41
> IMO the problem is not caching per se, it's that it doesn't go away when it should

The issue with _any_ caching ever is rarely the caching itself but rather the side-effects it imposes, such as eager/late/incorrect cache invalidation, memory use, disk use, locking and resource management, etc. In any case, I don't want to derail this into a debate when there's a very pragmatic functioning workaround for the time being.

I don't want to speak for the maintainers of Sourcery, but I'd say your PR would be welcome in Sourcery if there aren't any obvious downsides, even if the solution isn't general enough to be applied upstream to SourceKitten.

---

That being said, if anyone wants to help optimize some of the string manipulation utilities in SourceKitten, I'd be very grateful! It would benefit [all projects](https://github.com/jpsim/SourceKitten#projects-built-with-sourcekitten) that consume SourceKitten. It'd be great to obviate the need for caching entirely.

**Comment by krzysztofzablocki** [comment] 2018-02-08 15:53
@tamasprezi want to make a pr? then me and @ilyapuchka we can use that to see how it affects our performance in private projects and whether it makes sense to use that

**Comment by lvsti** [comment] 2018-02-08 21:05
He (I mean I) will try to find time for it in the weekend :)

**Closed** 2018-03-09 19:08 UTC

**Comment by gpambrozio** [comment] 2019-07-29 17:46
This is still working for my project. Is there any guide on how to run sorcery in my project using xcode so that I can investigate this? Thanks.
