### ISSUE TITLE
Get attribute argument (property wrapper)

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1051] opened 2022-04-08 23:55 UTC
I have an attribute and I want to extract what is red-underlined in the picture. Is there a way to do this?
I want to extract `Human(name: "zoe", age: 23)`
Given:
```swift
protocol foo {
    @Foo(key: Human(name: "zoe", age: 23)) 
    var aa: Human {get set}
}

@propertyWrapper struct Foo<A> {
    let key: A
    ...
}

struct Human {
    let name: String
    let age: Int
}
```
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/14034942/162547417-36d6d880-28ed-4f05-bf74-dc4a7f502380.png">

For some reason arguments gives me this which is not what I want ( it has removed all " chars)
<img width="766" alt="image" src="https://user-images.githubusercontent.com/14034942/162547702-ebe77dfc-0ddb-4671-bdca-64a1b091213c.png">

**Comment by art-divin** [comment] 2024-03-28 19:13
Duplicate of #1043 and will be resolved as such 🤝 thank you for reporting, @Nikoloutsos !

**Closed by art-divin** 2024-03-28 19:13 UTC
