### ISSUE TITLE
Crash in specific edge case involving unicode characters

### ISSUE THREAD

**Issue by jconst** [krzysztofzablocki/Sourcery#432] opened 2017-11-01 19:58 UTC
While processing my small file [Matrix.swift](https://gist.github.com/jconst/9e56b8e4cc8a16f741850c7d2b1323df) (a pared-down version of [Surge](https://github.com/mattt/Surge)'s [Matrix.swift](https://github.com/mattt/Surge/blob/master/Sources/Surge/Matrix.swift)) as a source (not a template), Sourcery gave me this error:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
Illegal instruction: 4
```

Removing the non-ascii characters in my `description` getter fixed the problem. For the sake of debugging, I tried simplifying the file and surprisingly this was as small as i could make it while still reproducing the error:

```
class Foo {
  var blah: String {
    switch true {
      default:
        return "\(true) π"
    }
  }
}
```

Getting rid of the π character, the switch, the outer class, the string interpolation, or even changing the `var blah` to a func, all cleared up the error. Here's the trace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x000000010eef1280 libswiftCore.dylib`_swift_runtime_on_report
    frame #1: 0x000000010ef31361 libswiftCore.dylib`_swift_stdlib_reportFatalError + 113
    frame #2: 0x000000010eecdd2f libswiftCore.dylib`partial apply forwarder for closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in closure #2 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._fatalErrorMessage(Swift.StaticString, Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 63
    frame #3: 0x000000010ebf8b1b libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer<A>((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A + 187
    frame #4: 0x000000010ee81b01 libswiftCore.dylib`partial apply forwarder for closure #2 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._fatalErrorMessage(Swift.StaticString, Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 113
    frame #5: 0x000000010ebf8b1b libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer<A>((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A + 187
    frame #6: 0x000000010edacb10 libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage(Swift.StaticString, Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 96
  * frame #7: 0x000000010e443ac0 SourceKittenFramework`NSString.CacheContainer.location(byteOffset=91, self=0x00007fabf73072d0) at String+SourceKitten.swift:129
    frame #8: 0x000000010e447137 SourceKittenFramework`NSString.byteRangeToNSRange(start=57, length=34, self="class Foo {\n  var blah: String {\n    switch true {\n      default:\n        return \"\\(true) π\"\n    }\n  }\n}\n") at String+SourceKitten.swift:261
    frame #9: 0x000000010e447be2 SourceKittenFramework`NSString.substringWithByteRange(start=57, length=34, self="class Foo {\n  var blah: String {\n    switch true {\n      default:\n        return \"\\(true) π\"\n    }\n  }\n}\n") at String+SourceKitten.swift:312
    frame #10: 0x000000010e447ff4 SourceKittenFramework`@objc NSString.substringWithByteRange(start:length:) at String+SourceKitten.swift:0
    frame #11: 0x000000010e06312e Sourcery`closure #1 in Substring.extract($0=(offset = 57, length = 34), contents="class Foo {\n  var blah: String {\n    switch true {\n      default:\n        return \"\\(true) π\"\n    }\n  }\n}\n") at Substring.swift:60
    frame #12: 0x000000010e0632c6 Sourcery`partial apply for closure #1 in Substring.extract(from:contents:) at Substring.swift:0
    frame #13: 0x000000010e063307 Sourcery`thunk for @callee_owned (@unowned Int64, @unowned Int64) -> (@owned String?, @error @owned Error) at Substring.swift:0
    frame #14: 0x000000010e06342b Sourcery`partial apply for thunk for @callee_owned (@unowned Int64, @unowned Int64) -> (@owned String?, @error @owned Error) at Substring.swift:0
    frame #15: 0x000000010ec05647 libswiftCore.dylib`Swift.Optional.flatMap<A>((A) throws -> Swift.Optional<A1>) throws -> Swift.Optional<A1> + 263
    frame #16: 0x000000010e062c48 Sourcery`Substring.extract(source=6 key/value pairs, contents="class Foo {\n  var blah: String {\n    switch true {\n      default:\n        return \"\\(true) π\"\n    }\n  }\n}\n", self=key) at Substring.swift:60
    frame #17: 0x000000010dff274d Sourcery`FileParser.extract(substringIdentifier=key, source=6 key/value pairs, self=0x00007fabf550d9b0) at FileParser.swift:777
    frame #18: 0x000000010dfe0a8e Sourcery`FileParser.parseTypealiases(source=7 key/value pairs, containingType=0x00007fabf5407270, processed=1 value, self=0x00007fabf550d9b0) at FileParser.swift:627
    frame #19: 0x000000010dfef681 Sourcery`FileParser.walkDeclaration(source=7 key/value pairs, containingIn=some, foundEntry=0x000000010dfe32e0 Sourcery`partial apply forwarder for closure #1 (SourceKittenFramework.SwiftDeclarationKind, Swift.String, SourceryRuntime.AccessLevel, Swift.Array<Swift.String>, Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, Swift.Optional<Any>) -> Swift.Optional<Any> in Sourcery.FileParser.parseTypes(Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, processed: inout Swift.Array<Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>>) -> Swift.Array<SourceryRuntime.Type> at FileParser.swift, self=0x00007fabf550d9b0) at FileParser.swift:202
    frame #20: 0x000000010dfe18e4 Sourcery`FileParser.walkDeclarations(source=11 key/value pairs, containingIn=some, processed=0x00007fff51c1e488, foundEntry=0x000000010dfe32e0 Sourcery`partial apply forwarder for closure #1 (SourceKittenFramework.SwiftDeclarationKind, Swift.String, SourceryRuntime.AccessLevel, Swift.Array<Swift.String>, Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, Swift.Optional<Any>) -> Swift.Optional<Any> in Sourcery.FileParser.parseTypes(Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, processed: inout Swift.Array<Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>>) -> Swift.Array<SourceryRuntime.Type> at FileParser.swift, self=0x00007fabf550d9b0) at FileParser.swift:178
    frame #21: 0x000000010dfef460 Sourcery`FileParser.walkDeclaration(source=11 key/value pairs, containingIn=nil, foundEntry=0x000000010dfe32e0 Sourcery`partial apply forwarder for closure #1 (SourceKittenFramework.SwiftDeclarationKind, Swift.String, SourceryRuntime.AccessLevel, Swift.Array<Swift.String>, Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, Swift.Optional<Any>) -> Swift.Optional<Any> in Sourcery.FileParser.parseTypes(Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, processed: inout Swift.Array<Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>>) -> Swift.Array<SourceryRuntime.Type> at FileParser.swift, self=0x00007fabf550d9b0) at FileParser.swift:199
    frame #22: 0x000000010dfe18e4 Sourcery`FileParser.walkDeclarations(source=4 key/value pairs, containingIn=nil, processed=0x00007fff51c1ec60, foundEntry=0x000000010dfe32e0 Sourcery`partial apply forwarder for closure #1 (SourceKittenFramework.SwiftDeclarationKind, Swift.String, SourceryRuntime.AccessLevel, Swift.Array<Swift.String>, Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, Swift.Optional<Any>) -> Swift.Optional<Any> in Sourcery.FileParser.parseTypes(Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>, processed: inout Swift.Array<Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>>) -> Swift.Array<SourceryRuntime.Type> at FileParser.swift, self=0x00007fabf550d9b0) at FileParser.swift:178
    frame #23: 0x000000010dfe0817 Sourcery`FileParser.parseTypes(source=4 key/value pairs, processed=0x00007fff51c1ec60, self=0x00007fabf550d9b0) at FileParser.swift:167
    frame #24: 0x000000010dfdffb1 Sourcery`FileParser.parse(self=0x00007fabf550d9b0) at FileParser.swift:115
    frame #25: 0x000000010e02f4dd Sourcery`Sourcery.loadOrParse(parser=0x00007fabf550d9b0, cachesPath=0x000000010e03b5f0 Sourcery`partial apply forwarder for implicit closure #1 : @autoclosure () -> PathKit.Path in closure #6 (Sourcery.FileParser) -> SourceryRuntime.FileParserResult in closure #1 (Swift.Int, PathKit.Path) throws -> () in Sourcery.Sourcery.(parse in _DB5C4364BFA94633EE953DD412A08C30)(from: Swift.Array<PathKit.Path>, exclude: Swift.Array<PathKit.Path>, modules: Swift.Optional<Swift.Array<Swift.String>>) throws -> (types: SourceryRuntime.Types, inlineRanges: Swift.Array<(file: Swift.String, ranges: Swift.Dictionary<Swift.String, __C._NSRange>)>) at Sourcery.swift, self=0x00007fabf550a890) at Sourcery.swift:276
    frame #26: 0x000000010e02ed01 Sourcery`closure #6 in closure #1 in Sourcery.parse($0=0x00007fabf550d9b0, self=0x00007fabf550a890, from=Sourcery.Path @ 0x00007fff51c20858) at Sourcery.swift:234
    frame #27: 0x000000010e03b3b5 Sourcery`partial apply for closure #6 in closure #1 in Sourcery.parse(from:exclude:modules:) at Sourcery.swift:0
    frame #28: 0x000000010e030003 Sourcery`thunk for @callee_owned (@owned FileParser) -> (@owned FileParserResult) at Sourcery.swift:0
    frame #29: 0x000000010e03b44a Sourcery`partial apply for thunk for @callee_owned (@owned FileParser) -> (@owned FileParserResult) at Sourcery.swift:0
    frame #30: 0x000000010ede43ed libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[0] = Owned To Guaranteed> of (extension in Swift):Swift.Collection.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 4493
    frame #31: 0x000000010ebcbe02 libswiftCore.dylib`(extension in Swift):Swift.Collection.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 18
    frame #32: 0x000000010e08d679 Sourcery`Array.parallelMap<A>(transform=0x000000010e03b400 Sourcery`partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned Sourcery.FileParser) -> (@owned SourceryRuntime.FileParserResult) to @callee_owned (@in Sourcery.FileParser) -> (@out SourceryRuntime.FileParserResult) at Sourcery.swift, progress=nil, self=1 value) at Array+Parallel.swift:20
    frame #33: 0x000000010e02d40a Sourcery`closure #1 in Sourcery.parse(index=0, from=Sourcery.Path @ 0x00007fff51c20858, exclude=0 values, modules=nil, self=0x00007fabf550a890, allResults=0x00007fff51c20d30) at Sourcery.swift:241
    frame #34: 0x000000010e03ab42 Sourcery`partial apply for closure #1 in Sourcery.parse(from:exclude:modules:) at Sourcery.swift:0
    frame #35: 0x000000010e0306fb Sourcery`thunk for @callee_owned (@unowned Int, @in Path) -> (@error @owned Error) at Sourcery.swift:0
    frame #36: 0x000000010e03abe3 Sourcery`partial apply for thunk for @callee_owned (@unowned Int, @in Path) -> (@error @owned Error) at Sourcery.swift:0
    frame #37: 0x000000010edd0bb9 libswiftCore.dylib`function signature specialization <preserving fragile attribute, Arg[0] = Owned To Guaranteed> of (extension in Swift):Swift.Sequence.forEach((A.Element) throws -> ()) throws -> () + 345
    frame #38: 0x000000010ebb28ff libswiftCore.dylib`(extension in Swift):Swift.Sequence.forEach((A.Element) throws -> ()) throws -> () + 15
    frame #39: 0x000000010e0262b9 Sourcery`Sourcery.parse(from=1 value, exclude=0 values, modules=nil, self=0x00007fabf550a890) at Sourcery.swift:244
    frame #40: 0x000000010e025512 Sourcery`closure #3 in Sourcery.processFiles(source=sources, self=0x00007fabf550a890, templatesPaths=Sourcery.Paths @ 0x00007fff51c210c0, output=Sourcery.Path @ 0x00007fabf550adc0) at Sourcery.swift:69
    frame #41: 0x000000010e025df5 Sourcery`partial apply for closure #3 in Sourcery.processFiles(_:usingTemplates:output:) at Sourcery.swift:0
    frame #42: 0x000000010e0245d0 Sourcery`Sourcery.processFiles(source=sources, templatesPaths=Sourcery.Paths @ 0x00007fff51c217b8, output=Sourcery.Path @ 0x00007fff51c22080, self=0x00007fabf550a890) at Sourcery.swift:90
    frame #43: 0x000000010e010640 Sourcery`closure #1 in runCLI(watcherEnabled=false, disableCache=false, verboseLogging=false, quiet=false, prune=false, sources=1 value, templates=1 value, output=Sourcery.Path @ 0x00007fff51c22bc0, configPath=Sourcery.Path @ 0x00007fff51c22c40, args=Sourcery.CustomArguments @ 0x00007fff51c227f8) at main.swift:167
    frame #44: 0x000000010e01116c Sourcery`thunk for @callee_owned (@unowned Bool, @unowned Bool, @unowned Bool, @unowned Bool, @unowned Bool, @owned [Path], @owned [Path], @in Path, @in Path, @owned CustomArguments) -> (@error @owned Error) at main.swift:0
    frame #45: 0x000000010e011aaf Sourcery`partial apply for thunk for @callee_owned (@unowned Bool, @unowned Bool, @unowned Bool, @unowned Bool, @unowned Bool, @owned [Path], @owned [Path], @in Path, @in Path, @owned CustomArguments) -> (@error @owned Error) at main.swift:0
    frame #46: 0x000000010e1f4f53 Commander`closure #1 in command<A, B, C, D, E, F, G, H, I, J>(parser=0x00007fabf7301880, descriptor=<unavailable>, descriptor1=<unavailable>, descriptor2=<unavailable>, descriptor3=<unavailable>, descriptor4=<unavailable>, descriptor5=<unavailable>, descriptor6=<unavailable>, descriptor7=<unavailable>, descriptor8=<unavailable>, descriptor9=<unavailable>, closure=0x000000010e0119d0 Sourcery`partial apply forwarder for reabstraction thunk helper from @callee_owned (@unowned Swift.Bool, @unowned Swift.Bool, @unowned Swift.Bool, @unowned Swift.Bool, @unowned Swift.Bool, @owned Swift.Array<PathKit.Path>, @owned Swift.Array<PathKit.Path>, @in PathKit.Path, @in PathKit.Path, @owned Sourcery.CustomArguments) -> (@error @owned Swift.Error) to @callee_owned (@in Swift.Bool, @in Swift.Bool, @in Swift.Bool, @in Swift.Bool, @in Swift.Bool, @in Swift.Array<PathKit.Path>, @in Swift.Array<PathKit.Path>, @in PathKit.Path, @in PathKit.Path, @in Sourcery.CustomArguments) -> (@error @owned Swift.Error) at main.swift) at Commands.swift:404
    frame #47: 0x000000010e1f5f32 Commander`partial apply for closure #1 in command<A, B, C, D, E, F, G, H, I, J>(_:_:_:_:_:_:_:_:_:_:_:) at Commands.swift:0
    frame #48: 0x000000010e1d2671 Commander`AnonymousCommand.run(parser=0x00007fabf7301880, self=(closure = 0x000000010e1f5b20 Commander`partial apply forwarder for closure #1 (Commander.ArgumentParser) throws -> () in Commander.command<A, B, C, D, E, F, G, H, I, J where A: Commander.ArgumentDescriptor, B: Commander.ArgumentDescriptor, C: Commander.ArgumentDescriptor, D: Commander.ArgumentDescriptor, E: Commander.ArgumentDescriptor, F: Commander.ArgumentDescriptor, G: Commander.ArgumentDescriptor, H: Commander.ArgumentDescriptor, I: Commander.ArgumentDescriptor, J: Commander.ArgumentDescriptor>(A, B, C, D, E, F, G, H, I, J, (A.ValueType, B.ValueType, C.ValueType, D.ValueType, E.ValueType, F.ValueType, G.ValueType, H.ValueType, I.ValueType, J.ValueType) throws -> ()) -> Commander.CommandType at Commands.swift)) at Command.swift:10
    frame #49: 0x000000010e1d2716 Commander`protocol witness for CommandType.run(_:) in conformance AnonymousCommand at Command.swift:0
    frame #50: 0x000000010e1d377a Commander`CommandType.run(version="0.9.0", self=) at CommandRunner.swift:24
    frame #51: 0x000000010e00ea1c Sourcery`runCLI() at main.swift:177
    frame #52: 0x000000010e00bae3 Sourcery`main at main.swift:186
    frame #53: 0x00007fffc97ab235 libdyld.dylib`start + 1
    frame #54: 0x00007fffc97ab235 libdyld.dylib`start + 1
```

The crash occurs at line 129 of String+SourceKitten.swift, so let me know if i should move this issue over there.

I'm running sourcery with something like this:
```
./sourcery --sources /folder/with/just/Matrix/ --templates /empty/folder --output /empty/folder
```

And swift --version gives me this:
```
Apple Swift version 4.0 (swiftlang-900.0.65.2 clang-900.0.37)
Target: x86_64-apple-macosx10.9
```

Thanks!

**Comment by ilyapuchka** [comment] 2017-11-04 23:07
Hi, @jconst 
I looked into this issue and it seems like bug in SourceKit. 

With your code snippet it returns the same length for case statement no matter how many white spaces are used in the string _after_ interpolation. So it might be even not related to unicode as it is only reproduces with string interpolation. You can reproduce that with this command:

`sourcekitten structure --text 'class Foo { var blah: String { switch { default: return "\(true) π" }}}'`

It will always give 26 for length of case statement:

```json
"key.kind" : "source.lang.swift.stmt.case",
"key.offset" : 40,
"key.length" : 26
```

At the same time when unicode character comes before string interpolation length is completely different.

`sourcekitten structure --text 'class Foo { var blah: String { switch { default: return "π \(true)" }}}'`

```json
"key.kind" : "source.lang.swift.stmt.case",
"key.offset" : 40,
"key.length" : 32
```

but again adding whitespaces after string interpolation does not change the length, which will probably give wrong results fro strings extraction.

/cc @jpsim

**Comment by jpsim** [comment] 2017-11-06 04:46
Can you please file an issue on SourceKitten so we can look into this?

**Comment by ilyapuchka** [comment] 2018-03-09 19:08
Closing as this is caused by SourceKit bug.

**Closed by ilyapuchka** 2018-03-09 19:08 UTC
