### ISSUE TITLE
Incorrect attributes when @available have message

### ISSUE THREAD

**Issue by EkkoG** [krzysztofzablocki/Sourcery#1122] opened 2023-01-02 12:46 UTC
With code like this

```
@available(iOS, introduced: 2.0, deprecated: 12.0, message: "No longer supported; please adopt WKWebView.")
@_Concurrency.MainActor open class UIWebView : UIView, NSCoding, UIScrollViewDelegate {
}
```
The type attributes.available will return this

```
[@available(iOS, introduced: 2.0, deprecated: 12.0, message: \)]
```

Env

Sourcery: 1.9.2
Xcode: Version 14.2
macOS: 13.1 (22C65)

**Comment by art-divin** [comment] 2023-07-29 10:19
With the following stencil:

```
<%_ for type in types.classes { -%>
    // <%= type.attributes %>
<%_ } -%>
```

and latest sourcery branch (master) I cannot reproduce this.

Closing, please reopen if needed 🙏🏻

**Closed by art-divin** 2023-07-29 10:19 UTC
