### ISSUE TITLE
Error executing via build-phases ${parent_path}

### ISSUE THREAD

**Issue by txaiwieser** [krzysztofzablocki/Sourcery#176] opened 2017-03-02 17:46 UTC
I had an old version of Sourcery in a project, and today after I updated to 0.6.8 I'm having this error
Coudn't figure out why. I've already updated my templates using CLI. Bug when using via build-phases I get this error:
```
: line 6: 13376 Illegal instruction: 4  "${parent_path}"/Sourcery.app/Contents/MacOS/Sourcery "$@"
Command /bin/sh failed with exit code 132
```
This is my shell-script
```
"$SRCROOT/Frameworks/Sourcery/bin/sourcery" "${SRCROOT}/Warren" "${SRCROOT}/Frameworks/Sourcery/Templates" "${SRCROOT}/Frameworks/Sourcery/Sourcery.generated.swift"
```
Any info?
Thank you!

**Comment by txaiwieser** [comment] 2017-03-02 19:00
I found a similar issue, but still couldnt make it work :/

#35

**Comment by txaiwieser** [comment] 2017-03-02 19:22
Also, #130

**Comment by krzysztofzablocki** [comment] 2017-03-05 08:18
try clearing the cache, there was a bug in old version of Sourcery so when switching you might need to clean it by hand, remove folder `~/Library/Caches/Sourcery/`

**Comment by txaiwieser** [comment] 2017-03-06 14:24
Cleaning the cache didn't work either, I've tried everything I could think of :/
same error: 
```
line 6:  1137 Illegal instruction: 4  "${parent_path}"/Sourcery.app/Contents/MacOS/Sourcery "$@"
```

**Comment by krzysztofzablocki** [comment] 2017-03-06 14:31
the paths setup seems a little weird to me, how did you install the tool?
Can you try pointing the output to a folder rather than a single file?

**Comment by txaiwieser** [comment] 2017-03-06 14:42
I downloaded the last .zip from release. I have a folder structure inside my proj
../Frameworks/
            ..bin/
            ..Templates/
and on the xcode build-phases I created the script, it was working until I updated last week

I did try changing the output to a folder instead of a .swift file. still results in the same error when calling the app from the script.

**Comment by krzysztofzablocki** [comment] 2017-03-07 07:08
@txaiwieser can you try building from source and running on your codebase ? its hard to tell what is happening without that

**Comment by txaiwieser** [comment] 2017-03-07 14:07
I really appreciate your help! Thanks!
I build and then ran from source and got more infos

```
Scanning sources...
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal WEBSITE_LINK"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal API_VERSION"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal KEYCHAIN_KEY"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal KEYCHAIN_TOKEN_STRING"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal FB_PAGE_ID"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal TW_PAGE_ID"
GitHub/Warren-iOS/Warren/Core/MainDefines.swift: Unsupported entry "internal varGlobal INSTABUG_TOKEN"
GitHub/Warren-iOS/Warren/Utilities/Delay.swift: Unsupported entry "internal functionFree delay(_:closure:)"
GitHub/Warren-iOS/Warren/Utilities/DictionaryConvertible.swift: Unsupported entry "private functionFree parseDictionary(_:)"
GitHub/Warren-iOS/Warren/Flows/Application/AppDelegate.swift: Unsupported entry "internal varGlobal IS_BETA_SETTINGS_ENABLED"
GitHub/Warren-iOS/Warren/Flows/Application/AppDelegate.swift: Unsupported entry "internal varGlobal Log"
GitHub/Warren-iOS/Warren/Flows/Application/AppDelegate.swift: Unsupported entry "internal varGlobal is_iPhone4s"
GitHub/Warren-iOS/Warren/Flows/Application/AppDelegate.swift: Unsupported entry "internal varGlobal is_iPhoneLargeWidth"
GitHub/Warren-iOS/Warren/Flows/Builder/BuilderDisplayViewController.swift: Unsupported entry "internal varGlobal BUILDER_TOP_LAYOUT_LENGHT"
GitHub/Warren-iOS/Warren/Flows/Builder/Fourth Step/BuilderS4MainViewController.swift: Unsupported entry "private functionFree saveInputAnswer(rawValue:key:)"
GitHub/Warren-iOS/Warren/Core/Rest/PortfoliosServices/PortfoliosEndPoint.swift: parseEnumCase: Unable to extract enum body from ["key.nameoffset": 326, "key.accessibility": "source.lang.swift.accessibility.internal", "key.length": 15, "key.name": "get", "key.kind": "source.lang.swift.decl.enumelement", "key.namelength": 3, "key.offset": 326]
GitHub/Warren-iOS/Warren/Extensions/BaseMappable+OneLevelJSONWithPrefix.swift: Unsupported entry "private functionFree flatMapAddingPrefix(result:json:subKeyPrefix:)"
GitHub/Warren-iOS/Warren/Flows/Builder/Second Step/BuilderS2MainViewController.swift: Unsupported entry "private functionFree saveInputAnswer(_:key:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree +(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree +=(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree -(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree -=(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree *(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree *=(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree *(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree *=(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree /(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree /=(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree /(_:_:)"
GitHub/Warren-iOS/Warren/Extensions/CGSize+Extensions.swift: Unsupported entry "public functionFree /=(_:_:)"
GitHub/Warren-iOS/Warren/Core/Model/Types/ExposedPersonType.swift: parseEnumCase: Unable to extract enum body from ["key.nameoffset": 53, "key.accessibility": "source.lang.swift.accessibility.internal", "key.length": 4, "key.name": "none", "key.kind": "source.lang.swift.decl.enumelement", "key.namelength": 4, "key.offset": 53]
GitHub/Warren-iOS/Warren/Extensions/SnapKit+Extensions.swift: parseEnumCase: Unable to extract enum body from ["key.nameoffset": 150, "key.accessibility": "source.lang.swift.accessibility.internal", "key.elements": [["key.kind": "source.lang.swift.structure.elem.init_expr", "key.offset": 161, "key.length": 4]], "key.length": 15, "key.name": "required", "key.kind": "source.lang.swift.decl.enumelement", "key.namelength": 8, "key.offset": 150]
GitHub/Warren-iOS/Warren/Flows/Builder/Third Step/BuilderS3EditInputViewController.swift: Unsupported entry "private functionFree internalSaveAction()"
GitHub/Warren-iOS/Warren/Utilities/OptionalAssignmentOperator.swift: Unsupported entry "internal functionFree =??(_:_:)"
GitHub/Warren-iOS/Warren/Utilities/OptionalAssignmentOperator.swift: Unsupported entry "internal functionFree =??(_:_:)"
GitHub/Warren-iOS/Warren/Utilities/OptionalAssignmentOperator.swift: Unsupported entry "internal functionFree =??(_:_:)"
fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    libswiftCore.dylib                 0x000000010cffbce0 swift_reportError + 132
1    libswiftCore.dylib                 0x000000010d019090 _swift_stdlib_reportFatalError + 61
2    libswiftCore.dylib                 0x000000010ce0f0c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
3    libswiftCore.dylib                 0x000000010cf8b230 partial apply for (_fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #2) + 109
4    libswiftCore.dylib                 0x000000010ce0f0c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
5    libswiftCore.dylib                 0x000000010cf433f0 specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 96
6    SourceKittenFramework              0x000000010cae5820 NSString.CacheContainer.location(fromByteOffset : Int) -> Int + 3227
7    SourceKittenFramework              0x000000010caea330 NSString.byteRangeToNSRange(start : Int, length : Int) -> _NSRange? + 134
8    SourceKittenFramework              0x000000010caead90 NSString.substringWithByteRange(start : Int, length : Int) -> String? + 60
9    SourceKittenFramework              0x000000010caeb200 @objc NSString.substringWithByteRange(start : Int, length : Int) -> String? + 57
10   Sourcery                           0x000000010c76ba30 Substring.(extract(from : [String : SourceKitRepresentable], contents : String) -> String?).(closure #1) + 98
11   Sourcery                           0x000000010c76bbb0 partial apply for Substring.(extract(from : [String : SourceKitRepresentable], contents : String) -> String?).(closure #1) + 101
12   Sourcery                           0x000000010c76bc20 thunk + 68
13   Sourcery                           0x000000010c76bd40 partial apply for thunk + 89
14   libswiftCore.dylib                 0x000000010ce178e0 Optional.flatMap<A> ((A) throws -> A1?) throws -> A1? + 354
15   Sourcery                           0x000000010c76b4e0 Substring.extract(from : [String : SourceKitRepresentable], contents : String) -> String? + 482
16   Sourcery                           0x000000010c6db4d0 FileParser.extract(Substring, from : [String : SourceKitRepresentable], contents : String) -> String? + 203
17   Sourcery                           0x000000010c6c5680 FileParser.parseTypealiases(from : [String : SourceKitRepresentable], containingType : Type?, processed : [[String : SourceKitRepresentable]]) -> [Typealias] + 2151
18   Sourcery                           0x000000010c6cf720 FileParser.walkDeclaration(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 5002
19   Sourcery                           0x000000010c6c6200 FileParser.walkDeclarations(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, processed : inout [[String : SourceKitRepresentable]], foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 1427
20   Sourcery                           0x000000010c6cf720 FileParser.walkDeclaration(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 4473
21   Sourcery                           0x000000010c6c6200 FileParser.walkDeclarations(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, processed : inout [[String : SourceKitRepresentable]], foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 1427
22   Sourcery                           0x000000010c6cf720 FileParser.walkDeclaration(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 4473
23   Sourcery                           0x000000010c6c6200 FileParser.walkDeclarations(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, processed : inout [[String : SourceKitRepresentable]], foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 1427
24   Sourcery                           0x000000010c6cf720 FileParser.walkDeclaration(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 4473
25   Sourcery                           0x000000010c6c6200 FileParser.walkDeclarations(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, processed : inout [[String : SourceKitRepresentable]], foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 1427
26   Sourcery                           0x000000010c6cf720 FileParser.walkDeclaration(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 4473
27   Sourcery                           0x000000010c6c6200 FileParser.walkDeclarations(source : [String : SourceKitRepresentable], containingIn : (Any, [String : SourceKitRepresentable])?, processed : inout [[String : SourceKitRepresentable]], foundEntry : (SwiftDeclarationKind, String, AccessLevel, [String], [String : SourceKitRepresentable], Any?) -> Any?) -> () + 1427
28   Sourcery                           0x000000010c6c5500 FileParser.parseTypes([String : SourceKitRepresentable], processed : inout [[String : SourceKitRepresentable]]) -> [Type] + 225
29   Sourcery                           0x000000010c6c4c10 FileParser.parse() -> FileParserResult + 577
30   Sourcery                           0x000000010c714f90 Sourcery.loadOrParse(parser : FileParser, cachesPath : Path) -> FileParserResult + 1683
31   Sourcery                           0x000000010c714ea0 Sourcery.(parse(from : Path) throws -> (types : [Type], inlineRanges : [(file : String, ranges : [String : _NSRange])])).(closure #5) + 189
32   Sourcery                           0x000000010c715f00 thunk + 30
33   Sourcery                           0x000000010c71ccc0 partial apply for thunk + 81
34   libswiftCore.dylib                 0x000000010cded790 Collection.map<A> ((A.Iterator.Element) throws -> A1) throws -> [A1] + 838
35   Sourcery                           0x000000010c78df10 Array.(parallelMap<A> ((A) -> A1, progress : (Int) -> ()?) -> [A1]).(closure #1) + 647
36   Sourcery                           0x000000010c78e8d0 partial apply for Array.(parallelMap<A> ((A) -> A1, progress : (Int) -> ()?) -> [A1]).(closure #1) + 231
37   Sourcery                           0x000000010c78e3f0 _TTRg__rXFo___XFdCb___ + 39
38   libdispatch.dylib                  0x00007fffb5adfeeb _dispatch_call_block_and_release + 12
39   libdispatch.dylib                  0x00007fffb5ad70b0 _dispatch_client_callout + 8
40   libdispatch.dylib                  0x00007fffb5aed765 _dispatch_queue_serial_drain + 209
41   libdispatch.dylib                  0x00007fffb5adf8c3 _dispatch_queue_invoke + 1046
42   libdispatch.dylib                  0x00007fffb5ae5f7f _dispatch_queue_override_invoke + 369
43   libdispatch.dylib                  0x00007fffb5ad8c94 _dispatch_root_queue_drain + 476
44   libdispatch.dylib                  0x00007fffb5ad8be4 _dispatch_worker_thread3 + 99
45   libsystem_pthread.dylib            0x00007fffb5d241ff _pthread_wqthread + 1299
46   libsystem_pthread.dylib            0x00007fffb5d241e0 start_wqthread + 13
Illegal instruction: 4
```

**Comment by krzysztofzablocki** [comment] 2017-03-07 16:09
so its parsing issue, you should be able to figure out which function / file triggers it, that way you might be able to share it with us (or write reproducible failing test)

**Comment by txaiwieser** [comment] 2017-03-09 13:12
Just isolate some of the errors, still have others to work, but already have this one #181

**Comment by krzysztofzablocki** [comment] 2017-04-17 16:55
this should be fixed on master, please re-open if not

**Closed by krzysztofzablocki** 2017-04-17 16:55 UTC
Labels: bug

**Comment by lynchrb** [comment] 2018-03-17 10:32
I'm experiencing this issue with 0.10.1 (the binary from the website). How do I isolate which file/function is causing the crash so I can report it?

**Comment by ilyapuchka** [comment] 2018-03-17 11:52
You should pass sources, templates and output using --sources, --templates and --output. I don't see any of this. I'm using 0.10.1 version without issues

Ilya Puchka

Отправлено с iPhone

**Comment by lynchrb** [comment] 2018-03-17 12:16
My invocation and results look like this: 
```
./Pods/Sourcery/bin/sourcery --sources TripFiles/ --templates Templates/ --output TripFiles/AutoGenerated/ --watch -v
No config file provided or it does not exist. Using command line arguments.
Scanning sources...
Found "extension UIViewController" of type for which there is no original type declaration information.
Found "extension Error" of type for which there is no original type declaration information.
Found "extension UIResponder" of type for which there is no original type declaration information.
Found "extension SORelativeDateTransformer" of type for which there is no original type declaration information.
Found "extension String" of type for which there is no original type declaration information.
Found "extension GAIDictionaryBuilder" of type for which there is no original type declaration information.
Found "extension URL" of type for which there is no original type declaration information.
Found "extension CLLocationCoordinate2D: Hashable" of type for which there is no original type declaration information.
Found "extension ListDisplayable" of type for which there is no original type declaration information.
Found "extension UIScreen" of type for which there is no original type declaration information.
Found "extension CLLocation" of type for which there is no original type declaration information.
Found "extension Date" of type for which there is no original type declaration information.
Found "extension NSDate" of type for which there is no original type declaration information.
Found "extension CABasicAnimation" of type for which there is no original type declaration information.
Found "extension Notification.Name" of type for which there is no original type declaration information.
Found "extension EditTripViewController" of type for which there is no original type declaration information.
Found "extension NSObject: BroadEquatable" of type for which there is no original type declaration information.
Found "extension Crashlytics" of type for which there is no original type declaration information.
Found "extension Measurement" of type for which there is no original type declaration information.
Found "extension UserDefaults" of type for which there is no original type declaration information.
Found "extension DefaultsKeys" of type for which there is no original type declaration information.
Found "extension UIFont" of type for which there is no original type declaration information.
Found "extension UIScrollView" of type for which there is no original type declaration information.
Found "extension FetchableStoredObject" of type for which there is no original type declaration information.
Found "extension UIColor" of type for which there is no original type declaration information.
Found "extension UIView" of type for which there is no original type declaration information.
Found "extension RestClient" of type for which there is no original type declaration information.
Found "extension UIWindow" of type for which there is no original type declaration information.
Found "extension UITextField" of type for which there is no original type declaration information.
Found "extension Array" of type for which there is no original type declaration information.
Found "extension NSManagedObject: SafeFetchRequest" of type for which there is no original type declaration information.
Found "extension NSManagedObjectContext" of type for which there is no original type declaration information.
Found "extension UICollectionView" of type for which there is no original type declaration information.
Found "extension UITableView" of type for which there is no original type declaration information.
Found "extension PHAsset: NativeMediaAsset" of type for which there is no original type declaration information.
Found "extension PhotoGroupViewController" of type for which there is no original type declaration information.
Found "extension SwiftHelpers" of type for which there is no original type declaration information.
Found "extension SPGooglePlacesAutocompletePlace: SearchLocationResult" of type for which there is no original type declaration information.
Found "extension Foundation.Notification.Name" of type for which there is no original type declaration information.
Found "extension UITextView: TextControl" of type for which there is no original type declaration information.
Found "extension UserConnectionType: CustomStringConvertible" of type for which there is no original type declaration information.
Found "extension AddHometownViewController" of type for which there is no original type declaration information.
Found "extension LikesViewController" of type for which there is no original type declaration information.
Found "extension UIButton" of type for which there is no original type declaration information.
Found "extension UIBarButtonItem" of type for which there is no original type declaration information.
Found "extension CGSize" of type for which there is no original type declaration information.
Found "extension CGRect" of type for which there is no original type declaration information.
Found "extension PHPhotoLibrary" of type for which there is no original type declaration information.
Found "extension ModuleNoteViewController: ModuleItemContainer" of type for which there is no original type declaration information.
Found "extension ModuleCheckinViewController: ModuleItemContainer" of type for which there is no original type declaration information.
Found "extension ModuleMediaItemViewController: ModuleItemContainer" of type for which there is no original type declaration information.
Found "extension FTGooglePlacesAPINearbySearchRequest" of type for which there is no original type declaration information.
Found "extension ImageContainer" of type for which there is no original type declaration information.
Found "extension UINavigationController" of type for which there is no original type declaration information.
Found "extension ModuleUserActionHeaderViewController" of type for which there is no original type declaration information.
Found "extension ListHelper" of type for which there is no original type declaration information.
Found "extension Collection" of type for which there is no original type declaration information.
Found "extension ModuleItem: UserActionableItem" of type for which there is no original type declaration information.
Found "extension EditReviewViewController" of type for which there is no original type declaration information.
Found "extension Dictionary" of type for which there is no original type declaration information.
Found "extension Optional: OptionalType" of type for which there is no original type declaration information.
Found "extension RangeReplaceableCollection" of type for which there is no original type declaration information.
Found "extension MutableCollection" of type for which there is no original type declaration information.
Found "extension Sequence" of type for which there is no original type declaration information.
Found "extension DispatchQueue: AsyncBlockPerformer" of type for which there is no original type declaration information.
Found "extension Link" of type for which there is no original type declaration information.
Found "extension NSException" of type for which there is no original type declaration information.
Found "extension NSString: TextContainer" of type for which there is no original type declaration information.
Found "extension NSAttributedString: TextContainer" of type for which there is no original type declaration information.
Found "extension ListListViewController" of type for which there is no original type declaration information.
Found "extension PrivacyType" of type for which there is no original type declaration information.
Found "extension FileManager" of type for which there is no original type declaration information.
./Pods/Sourcery/bin/sourcery: line 6:  3988 Illegal instruction: 4  "${parent_path}"/Sourcery.app/Contents/MacOS/Sourcery "$@"
```

**Comment by ilyapuchka** [comment] 2018-03-17 12:30
@lynchrb disregard my comment, I mixed few messages from GitHub.
Try to narrow down your scanned sources to find file that causes issue.

**Comment by lynchrb** [comment] 2018-03-17 20:11
The crash was caused by a dictionary whose value is a function. This is the minimal necessary declaration:

```
var dict = Dictionary<String, () -> Void>()
```

**Comment by ilyapuchka** [comment] 2018-03-17 20:11
Thanks, I'll look at that

**Comment by lynchrb** [comment] 2018-03-17 20:14
Np. Is there a way I can have Sourcery ignore this declaration for now? (Without having to white list all of the other files in the project?)

**Comment by ilyapuchka** [comment] 2018-03-17 20:16
You can exclude individual files, but I'm afraid it's only supported via config file. I'll add this option to CLI
