### ISSUE TITLE
Auto inline into a file with several types introduce the annotations wherever.

### ISSUE THREAD

**Issue by minuscorp** [krzysztofzablocki/Sourcery#659] opened 2018-08-06 13:45 UTC
So I'm having issues with `// sourcery:inline:auto:{{ type.name }}` annotations. It seems that when more than one type is in the same file which gets all the requirements, Sourcery injects the code wherever (without any pattern that I could've found).

This is the example stencil:
```
{% for type in types.all where type.name|lowercase|!contains:"test" and type.implements.Action or type.implements.CompletableAction or type.implements.EmptyAction %}

    // sourcery:inline:auto:{{ type.name }}.AutoEquatableAction
    func someImportantFuncRequiredByTheProtocol() {
    }
   // sourcery:end
{% endfor %}
```
Imagine a file which has the following content:
```swift
class GetProvincesAction: Action {
}
class GetProvincesCompleteAction: CompletableAction {
}
class GetPersonalDataCompleteAction: CompletableAction {
}
```

It just messes up everything and inserts the code mixed. Just once you have moved the wrong placed annotations Sourcery does not mix them in further calls.

Any suggestion? I think this is a bug with the reading of the inline annotations 🤔

**Comment by minuscorp** [comment] 2018-08-31 07:09
I could try to give this a try if someone could give me some insight on how the process of embedding the `inline` annotations work.

**Comment by jcislinsky** [comment] 2019-04-23 11:31
+1

**Comment by krzysztofzablocki** [comment] 2021-03-07 06:54
duplicate of #601

**Closed by krzysztofzablocki** 2021-03-07 06:54 UTC
Labels: bug, help wanted
