### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate”

### ISSUE THREAD

**Issue by brannpark** [krzysztofzablocki/Sourcery#746] opened 2019-04-03 09:51 UTC
Hi, 

I have a following issue with Xcode 10.2, Mac OS Mojave 10.14.4, and Sourcery 0.16.0.

```
$ sourcery --config mocky.yml

error: Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/brannpark/Library/Caches/Sourcery/Mock.swifttemplate/5Dp3a9vTHHHYxDu9t5KHfVXiVAsjOAEWk3HrPc2Gnbg%3D, NSFilePath=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7fe69eac3a00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/brannpark/Library/Caches/Sourcery/Mock.swifttemplate/5Dp3a9vTHHHYxDu9t5KHfVXiVAsjOAEWk3HrPc2Gnbg%3D, NSFilePath=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7fe69eac3a00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}%
```

I tried to clean `~/Library/Caches/Sourcery`, `/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate`, but nothing helped.

The SourceFile(or directory?) "/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate" does not exist on that path. I have no idea how to fix it. 

`sourcery --config mocky.yml --disableCache`  also makes error with following stacktrace. 

```
2019-04-03 18:51:06.232 sourcery[67652:12198726] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2eaeccf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff59681a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2eaecb2b +[NSException raise:format:] + 201
	3   Foundation                          0x00007fff30cd299f -[NSConcreteTask launchWithDictionary:error:] + 1291
	4   sourcery                            0x000000010186f313 $SSo6NSTaskC13SourcerySwiftE10runCommand33_97A733547C26B01DA3FEDC2EDE49AED9LL4path9arguments11environment20currentDirectoryPathAC13ProcessResultAELLVSS_SaySSGSDyS2SG0R3Kit0R0VSgtKFZTf4xnnnd_n + 1923
	5   sourcery                            0x000000010186a10b $S13SourcerySwift0B8TemplateC6renderySSypKF + 907
	6   sourcery                            0x00000001017a44b2 $S13SourcerySwift0B8TemplateC0A9Framework0C00A0AdEP6renderySS0A7Runtime0C7ContextCKFTW + 66
	7   sourcery                            0x00000001017c43c9 $S17SourceryFramework9GeneratorO8generate_8template9argumentsSS0A7Runtime5TypesC_AA8Template_pSDySSSo8NSObjectCGtKFZ + 425
	8   sourcery                            0x00000001017a981a $S8SourceryAAC8generate33_DB5C4364BFA94633EE953DD412A08C30LL_16forParsingResult10outputPathSS0A9Framework8Template_p_0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangest0N3Kit0N0VtKF + 826
	9   sourcery                            0x00000001017b9cf2 $S8SourceryAAC8generate33_DB5C4364BFA94633EE953DD412A08C30LL6source13templatePaths6output13parsingResultyAA6SourceO_AA0L0VAA6OutputV0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangesttKFy0A9Framework8Template_pKXEfU_Tf4nnxn_n + 98
	10  sourcery                            0x00000001017ba2d1 $S8SourceryAAC8generate33_DB5C4364BFA94633EE953DD412A08C30LL6source13templatePaths6output13parsingResultyAA6SourceO_AA0L0VAA6OutputV0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangesttKFTf4dxnnnn_n + 881
	11  sourcery                            0x00000001017bb6c6 $S8SourceryAAC12processFiles_14usingTemplates6output10forceParseSayAA13FolderWatcherO5LocalCGSgAA6SourceO_AA5PathsVAA6OutputVSaySSGtKF0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangestANKcfU1_Tf4nnnxn_n + 3542
	12  sourcery                            0x00000001017bc663 $S8SourceryAAC12processFiles_14usingTemplates6output10forceParseSayAA13FolderWatcherO5LocalCGSgAA6SourceO_AA5PathsVAA6OutputVSaySSGtKFTf4nxnnn_n + 1843
	13  sourcery                            0x0000000101783048 $S8Sourcery6runCLIyyFySb_S4bSay7PathKit0D0VGA3f2ESaySSGAgEtcfU_ + 2232
	14  sourcery                            0x0000000101783680 $SS5bSay7PathKit0A0VGA3d2CSaySSGAeCs5Error_pIegyyyyyggggnnggnzo_S5bA4d2c2eCsAF_pIegnnnnnnnnnnnnnnzo_TR032$S8Sourcery6runCLIyyFySb_S4bSay7A27Kit0D0VGA3f2ESaySSGAgEtcfU_Tf3nnnnnnnnnnnnnnpf_n + 80
	15  sourcery                            0x00000001016ee346 $S9Commander7commandyAA11CommandType_px_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_y05ValueD0Qz_ADQy_ADQy0_ADQy1_ADQy2_ADQy3_ADQy4_ADQy5_ADQy6_ADQy7_ADQy8_ADQy9_ADQy10_ADQy11_tKctAA18ArgumentDescriptorRzAaSR_AaSR0_AaSR1_AaSR2_AaSR3_AaSR4_AaSR5_AaSR6_AaSR7_AaSR8_AaSR9_AaSR10_AaSR11_r12_lFyAA0F6ParserCKcfU_ + 4518
	16  sourcery                            0x00000001016ee657 $S9Commander7commandyAA11CommandType_px_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_y05ValueD0Qz_ADQy_ADQy0_ADQy1_ADQy2_ADQy3_ADQy4_ADQy5_ADQy6_ADQy7_ADQy8_ADQy9_ADQy10_ADQy11_tKctAA18ArgumentDescriptorRzAaSR_AaSR0_AaSR1_AaSR2_AaSR3_AaSR4_AaSR5_AaSR6_AaSR7_AaSR8_AaSR9_AaSR10_AaSR11_r12_lFyAA0F6ParserCKcfU_TA + 279
	17  sourcery                            0x00000001016db343 $S9Commander16AnonymousCommandVAA0C4TypeA2aDP3runyyAA14ArgumentParserCKFTW + 51
	18  sourcery                            0x00000001016db793 $S9Commander11CommandTypePAAE3runys5NeverOSSSgF + 403
	19  sourcery                            0x000000010178278a $S8Sourcery6runCLIyyF + 2314
	20  sourcery                            0x00000001017811fd main + 61
	21  libdyld.dylib                       0x00007fff5aeaf3d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any idea?

**Comment by krzysztofzablocki** [comment] 2019-04-03 10:10
lets move this discussion to the existing ticket because this is duplicate of #745

**Closed by krzysztofzablocki** 2019-04-03 10:10 UTC

**Comment by strongSoda** [comment] 2025-03-05 14:11
[This might help](https://rref-calculator.com/blog/errordomain-nscocoaerrordomain-errormessage-could-not-find-the-specified-shortcut-errorcode-4/)
