### ISSUE TITLE
Error parsing reserved keywords as Enum cases

### ISSUE THREAD

**Issue by txaiwieser** [krzysztofzablocki/Sourcery#181] opened 2017-03-09 13:10 UTC
Steps to reproduce:
1) Try parsing any file with the following code
Any of the following Enum cases give a parsing error. (theres probably way more words, all reserved keywords maybe?)

```
enum Test {
    case none
    case get(id: String)
    case required
}
```

Thanks! 👍

**Comment by krzysztofzablocki** [comment] 2017-03-09 13:23
@ilyapuchka possible regression due to the changes we merged recently for the keywords?

**Comment by ilyapuchka** [comment] 2017-03-09 13:24
`¯\_(ツ)_/¯` maybe, I can take a quick look

**Comment by ilyapuchka** [comment] 2017-03-09 14:01
Yes, that's it. I will revert and implement a better way to handle this. There are some other minor issues in this case.

**Comment by ilyapuchka** [comment] 2017-03-25 12:40
I believe this should be fixed, please let us know if you find any other issues related to this @txaiwieser

**Closed by ilyapuchka** 2017-03-25 12:40 UTC
Labels: bug
